### ISSUE TITLE
Project headline: still points to http://code.google.com

### ISSUE THREAD

**Issue by kryger** [google/google-http-java-client#313]
As per the title. http://code.google.com redirects back here so clicking the link can cause confusion.

<img width="684" alt="screen shot 2015-11-29 at 22 32 31" src="https://cloud.githubusercontent.com/assets/1566028/11460693/2d42f4c0-96e9-11e5-8918-6724b26c2ed3.png">

Should be https://developers.google.com/api-client-library/java/google-http-java-client/, most likely?

**Comment by ejona86** [comment]
Oops. Thanks for pointing that out.

I swapped it to developers.google.com briefly, but it looked really ugly because the URL is so long, so I removed the URL altogether. For both oauth and http the URL is pretty long and the developer documentation link is reasonably findable in the README.md. But I'll probably leave the link for the api library as the link isn't as long and much harder to find in README.md.
