### ISSUE TITLE
Logging of HTTP requests and responses should be at lower log level.

### ISSUE THREAD

**Issue by tmccombs** [google/google-http-java-client#391]
Currently, the entire content of HTTP requests and responses are logged to the HttpTransport logger at `Level.CONFIG` which corresponds to INFO level in SLF4J. The responses can contain sensitive data including user names and email addresses, not to mention that it bloats logs if logging at INFO level. This seems like something that should probably be logged at a lower level.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free explain why you believe fixing it is essential for users of this client library.
