### ISSUE TITLE
Maven repository missing 1.24.1 parent artifact

### ISSUE THREAD

**Issue by pwilder** [google/google-http-java-client#441]
Apologies, if this is not the right place for this issue.

The google http-client library

`<dependency>
    <groupId>com.google.http-client</groupId>
    <artifactId>google-http-client</artifactId>
    <version>1.24.1</version>
</dependency>
`

references the following parent artifact:

` <groupId>com.google.http-client</groupId>
  <artifactId>google-http-client-parent</artifactId>
  <version>1.24.1</version>`

http://central.maven.org/maven2/com/google/http-client/google-http-client/1.24.1/google-http-client-1.24.1.pom

But the 1.24.1 parent artifact appears to be unavailable in the central.maven.org repository: https://mvnrepository.com/artifact/com.google.http-client/google-http-client-parent.

In my case this manifested as an error when using a different library which was automatically picking up the latest minor version upgrade of the google-http-client.

**Comment by garrettjonesgoogle** [comment]
It does exist: https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.24.1/

Yesterday it didn't exist because there was a problem with the release process, but we did get it released, just later than everything else.

One thing to be aware of is that sites like mvnrepository.com take some time to pick up updates. I recommend search.maven.org for searches because it seems to pick them up faster than other sites - it shows 1.24.1:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.http-client%22%20AND%20a%3A%22google-http-client-parent%22

**Comment by pwilder** [comment]
Can confirm. While my links still show a gap the actual downloading of the artifacts seems functional. As you suggest, it's likely a propagation delay. Closing the issue, thank you for your consideration.
